# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Novel

on:
  workflow_dispatch:
    inputs:
      targetAddress:
        description: 'Target address'
        required: true
        default: 'https://www.biqupai.com/78_78513/'
      targetRange:
        description: 'Target range'
        required: false
        default: '[:]'

jobs:
  Run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests BeautifulSoup4
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run novel
      run: |
        python ./novel.py ${{ github.event.inputs.targetAddress }}
